<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Game;
use App\Models\Genre;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        // Clear existing games first
        Game::truncate();

        $games = [
            [
                'title' => 'Spider-Man 2',
                'genre_id' => Genre::where('name', 'action')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.8,
                'max_players' => 1,
                'estimated_duration' => '15-20 hours',
                'description' => 'Experience the ultimate Spider-Man adventure with Peter Parker and Miles Morales.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/1c7b75d8ed9271516546560d219ad0b22ee0a263b4537bd8.png',
                'is_popular' => true,
                'is_new' => true,
                'release_date' => '2023-10-20',
                'is_active' => true
            ],
            [
                'title' => 'FIFA 24',
                'genre_id' => Genre::where('name', 'sports')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.2,
                'max_players' => 4,
                'estimated_duration' => '90 minutes',
                'description' => 'The world\'s game with HyperMotionV technology and authentic football experience.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202408/0817/4248a0d1a669210e5caf5174eda176c7883be2c9089fa106.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2023-09-29',
                'is_active' => true
            ],
            [
                'title' => 'Call of Duty: Modern Warfare III',
                'genre_id' => Genre::where('name', 'shooter')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.5,
                'max_players' => 4,
                'estimated_duration' => '6-8 hours',
                'description' => 'The direct sequel to 2022\'s Modern Warfare II continues the rebooted series.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202308/1722/15f4ab1e0fe6a37609b164362a653c0e5bcee98a861d0f10.png',
                'is_popular' => true,
                'is_new' => true,
                'release_date' => '2023-11-10',
                'is_active' => true
            ],
            [
                'title' => 'Gran Turismo 7',
                'genre_id' => Genre::where('name', 'racing')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.6,
                'max_players' => 2,
                'estimated_duration' => '20+ hours',
                'description' => 'The ultimate racing simulator with stunning graphics and realistic physics.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202109/1321/yZ7dpmjtHr1olhutHT57IFRh.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2022-03-04',
                'is_active' => true
            ],
            [
                'title' => 'God of War Ragnarök',
                'genre_id' => Genre::where('name', 'action')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.9,
                'max_players' => 1,
                'estimated_duration' => '25-30 hours',
                'description' => 'Kratos and Atreus embark on a mythic journey for answers before Ragnarök arrives.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2022-11-09',
                'is_active' => true
            ],
            [
                'title' => 'Tekken 8',
                'genre_id' => Genre::where('name', 'fighting')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.4,
                'max_players' => 2,
                'estimated_duration' => '2-3 hours',
                'description' => 'The legendary fighting game returns with stunning visuals and new mechanics.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202212/2101/CxnQHVI3gzboBTHqEEQVWZJ6.png',
                'is_popular' => true,
                'is_new' => true,
                'release_date' => '2024-01-26',
                'is_active' => true
            ],
            [
                'title' => 'Elden Ring',
                'genre_id' => Genre::where('name', 'rpg')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.7,
                'max_players' => 4,
                'estimated_duration' => '50+ hours',
                'description' => 'A fantasy action-RPG adventure set in the Lands Between.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202110/2000/aGhopp3MHppi7kooGE2Dtt8C.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2022-02-25',
                'is_active' => true
            ],
            [
                'title' => 'Horizon Forbidden West',
                'genre_id' => Genre::where('name', 'adventure')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.6,
                'max_players' => 1,
                'estimated_duration' => '30+ hours',
                'description' => 'Join Aloy as she braves the Forbidden West to find the source of a mysterious plague.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202107/3100/HO8vkO9pfXhwbHi5WHECQJdN.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2022-02-18',
                'is_active' => true
            ],
            [
                'title' => 'The Last of Us Part I',
                'genre_id' => Genre::where('name', 'action')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.8,
                'max_players' => 1,
                'estimated_duration' => '15 hours',
                'description' => 'Experience the emotional storytelling and refined gameplay of this acclaimed adventure.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202206/0720/eEczyEMDd2BLa3dtkGJVE9Id.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2022-09-02',
                'is_active' => true
            ],
            [
                'title' => 'Uncharted 4: A Thief\'s End',
                'genre_id' => Genre::where('name', 'adventure')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.7,
                'max_players' => 1,
                'estimated_duration' => '15 hours',
                'description' => 'Nathan Drake\'s greatest adventure in his final chapter.',
                'image_url' => 'https://image.api.playstation.com/vulcan/img/rnd/202011/1018/SGqMZHd7WWmN4XIcLfYMxJsc.png',
                'is_popular' => false,
                'is_new' => false,
                'release_date' => '2016-05-10',
                'is_active' => true
            ],
            [
                'title' => 'Cyberpunk 2077',
                'genre_id' => Genre::where('name', 'rpg')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.1,
                'max_players' => 1,
                'estimated_duration' => '25+ hours',
                'description' => 'An open-world action-adventure story set in Night City.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202111/3013/cKZ4tKNFj9C00giTzYtH8PF1.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2020-12-10',
                'is_active' => true
            ],
            [
                'title' => 'Street Fighter 6',
                'genre_id' => Genre::where('name', 'fighting')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.5,
                'max_players' => 2,
                'estimated_duration' => '3-5 hours',
                'description' => 'The evolution of fighting games with new mechanics and characters.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202211/1407/XFU0aPBvtm3W2od1ZvhByAOv.png',
                'is_popular' => true,
                'is_new' => true,
                'release_date' => '2023-06-02',
                'is_active' => true
            ],
            [
                'title' => 'Ghost of Tsushima',
                'genre_id' => Genre::where('name', 'action')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.7,
                'max_players' => 1,
                'estimated_duration' => '25+ hours',
                'description' => 'Forge a new path and wage an unconventional war for the freedom of Tsushima.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202106/2322/c16gs6a7lbAYzPf7ZTikbH1c.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2020-07-17',
                'is_active' => true
            ],
            [
                'title' => 'Civilization VI',
                'genre_id' => Genre::where('name', 'strategy')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.2,
                'max_players' => 6,
                'estimated_duration' => '20+ hours',
                'description' => 'Build an empire to stand the test of time.',
                'image_url' => 'https://image.api.playstation.com/vulcan/img/cfn/11307E56bIuRGrfv9ff8wwveWmV7uacpqb4r5zK5xUzdiF08CJhOdH49azqHHMk-KL_fSepb-A8Y9YG8ekp1y0PgRocP9v2l.png',
                'is_popular' => false,
                'is_new' => false,
                'release_date' => '2019-11-22',
                'is_active' => true
            ],
            [
                'title' => 'XCOM 2',
                'genre_id' => Genre::where('name', 'strategy')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.3,
                'max_players' => 1,
                'estimated_duration' => '35+ hours',
                'description' => 'Earth has changed and is now under alien rule. Fight back with tactical combat.',
                'image_url' => 'https://image.api.playstation.com/cdn/UP1001/CUSA04552_00/lILweNYnWE05ZrO0WVtrZBpJj0eiW9NNr2k0N4ALVCAEKMYNwIyufBp46kWTZDF4.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2016-09-27',
                'is_active' => true
            ],
            [
                'title' => 'Total War: Rome Remastered',
                'genre_id' => Genre::where('name', 'strategy')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.1,
                'max_players' => 1,
                'estimated_duration' => '40+ hours',
                'description' => 'Command ancient Rome in epic real-time strategy battles.',
                'image_url' => 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/885970/capsule_616x353.jpg',
                'is_popular' => false,
                'is_new' => true,
                'release_date' => '2021-04-29',
                'is_active' => true
            ],
            [
                'title' => 'Age of Empires II: Definitive Edition',
                'genre_id' => Genre::where('name', 'strategy')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.5,
                'max_players' => 8,
                'estimated_duration' => '15+ hours',
                'description' => 'The classic real-time strategy game returns with enhanced graphics.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202503/2719/a79d7324d5ed233b6a3fa9b4fbe7b60627b3bf897f42ca68.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2019-11-14',
                'is_active' => true
            ],
            [
                'title' => 'Crusader Kings III',
                'genre_id' => Genre::where('name', 'strategy')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.4,
                'max_players' => 1,
                'estimated_duration' => '50+ hours',
                'description' => 'Rule a medieval dynasty through the centuries.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202108/1607/czGau6hOvx9iQYOOkACdxqDl.png',
                'is_popular' => true,
                'is_new' => true,
                'release_date' => '2022-03-29',
                'is_active' => true
            ],
            [
                'title' => 'Command & Conquer Remastered',
                'genre_id' => Genre::where('name', 'strategy')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.0,
                'max_players' => 8,
                'estimated_duration' => '12+ hours',
                'description' => 'The legendary RTS returns with remastered graphics and audio.',
                'image_url' => 'https://upload.wikimedia.org/wikipedia/en/5/5b/Command_and_Conquer_Remastered_artwork.jpg',
                'is_popular' => false,
                'is_new' => false,
                'release_date' => '2020-06-05',
                'is_active' => true
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'genre_id' => Genre::where('name', 'adventure')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.8,
                'max_players' => 1,
                'estimated_duration' => '60+ hours',
                'description' => 'An epic tale of life in America at the dawn of the modern age.',
                'image_url' => 'https://image.api.playstation.com/cdn/UP1004/CUSA03041_00/Hpl5MtwQgOVF9vJqlfui6SDB5Jl4oBSq.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2018-10-26',
                'is_active' => true
            ],
            [
                'title' => 'The Witcher 3: Wild Hunt',
                'genre_id' => Genre::where('name', 'adventure')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.9,
                'max_players' => 1,
                'estimated_duration' => '100+ hours',
                'description' => 'A story-driven open world RPG set in a visually stunning fantasy universe.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202211/0711/kh4MUIuMmHlktOHar3lVl6rY.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2015-05-19',
                'is_active' => true
            ],
            [
                'title' => 'Spider-Man: Miles Morales',
                'genre_id' => Genre::where('name', 'adventure')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.6,
                'max_players' => 1,
                'estimated_duration' => '8-12 hours',
                'description' => 'Miles Morales discovers explosive powers that set him apart from his mentor.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202008/1020/T45iRN1bhiWcJUzST6UFGBvO.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2020-11-12',
                'is_active' => true
            ],
            [
                'title' => 'Ratchet & Clank: Rift Apart',
                'genre_id' => Genre::where('name', 'adventure')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.6,
                'max_players' => 1,
                'estimated_duration' => '11 hours',
                'description' => 'Go dimension-hopping with Ratchet and Clank.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202101/2921/DwVjpbKOsFOyPdNzmSTSWuxG.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2021-06-11',
                'is_active' => true
            ],
            [
                'title' => 'Need for Speed Heat',
                'genre_id' => Genre::where('name', 'racing')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.2,
                'max_players' => 8,
                'estimated_duration' => '12+ hours',
                'description' => 'Hustle by day and risk it all at night in Need for Speed Heat.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202209/2915/uZgA8iEoSMzNrbDsj6dZpnpu.png',
                'is_popular' => true,
                'is_new' => false,
                'release_date' => '2019-11-08',
                'is_active' => true
            ],
            [
                'title' => 'F1 23',
                'genre_id' => Genre::where('name', 'racing')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.4,
                'max_players' => 22,
                'estimated_duration' => '15+ hours',
                'description' => 'Be the last to brake in EA SPORTS F1 23, the official video game of the 2023 FIA Formula One World Championship.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202311/2816/6a8e9cca68894033f83c2994933badd089bd33591a8f20eb.png',
                'is_popular' => true,
                'is_new' => true,
                'release_date' => '2023-06-16',
                'is_active' => true
            ],
            [
                'title' => 'Dirt 5',
                'genre_id' => Genre::where('name', 'racing')->first()->id,
                'console_type' => 'ps5',
                'rating' => 4.1,
                'max_players' => 12,
                'estimated_duration' => '10+ hours',
                'description' => 'Blaze a trail on routes across the world, covering gravel, ice, snow and sand.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202010/2110/8ZEssUZl5TmCSdAV5C8mZuyY.png',
                'is_popular' => false,
                'is_new' => false,
                'release_date' => '2020-11-06',
                'is_active' => true
            ],
            [
                'title' => 'The Crew 2',
                'genre_id' => Genre::where('name', 'racing')->first()->id,
                'console_type' => 'ps4',
                'rating' => 4.0,
                'max_players' => 8,
                'estimated_duration' => '20+ hours',
                'description' => 'Join a crew of racers, stunt pilots, and street racers to conquer the motorsports world.',
                'image_url' => 'https://image.api.playstation.com/vulcan/ap/rnd/202106/1607/BfevxYujMvsVNJaY0SZJM0cq.png',
                'is_popular' => false,
                'is_new' => false,
                'release_date' => '2018-06-29',
                'is_active' => true
            ]
        ];

        foreach ($games as $gameData) {
            Game::create($gameData);
        }
    }
}
